apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.additionalSecretName" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.langfuse.encryptionKey | toString | b64enc }}