{{- if and (contains "puma" .Values.container.command) (contains "--control-url" .Values.container.command)}}
{{- $pumaport := regexFind "--control-url tcp://([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\:([0-9]{1,4})" .Values.container.command | split ":"}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Release.Name }}-istio-puma-port
  namespace: {{ .Release.Namespace | quote }}
spec:
  portLevelMtls:
    "{{ $pumaport._2 }}":
      mode: DISABLE
  selector:
    matchLabels:
      {{- include "docker-template.selectorLabels" . | nindent 6 }}
{{- end }}
