{{- if and (not .Values.bluegreen.enabled) .Values.keda.enabled -}}
{{- $fullName := include "docker-template.fullname" $ -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $fullName }}
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  fallback:
    failureThreshold: {{ .Values.keda.fallback.failureThreshold }}
    replicas: {{ .Values.keda.fallback.failureReplicas }}
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      # the name of the HPA to adopt - otherwise the keda admission webhook will fail this update
      name: {{ $fullName }}
      behavior:
        scaleUp:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleUp.stabilizationWindowSeconds }}
          policies:
          - type: {{ .Values.keda.hpa.scaleUp.policy.type }}
            value: {{ .Values.keda.hpa.scaleUp.policy.value }}
            periodSeconds: {{ .Values.keda.hpa.scaleUp.policy.periodSeconds }}
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleDown.stabilizationWindowSeconds }}
          policies:
          - type: {{ .Values.keda.hpa.scaleDown.policy.type }}
            value: {{ .Values.keda.hpa.scaleDown.policy.value }}
            periodSeconds: {{ .Values.keda.hpa.scaleDown.policy.periodSeconds }}
  {{- if .Values.keda.trigger }}
  triggers:
    - type: prometheus
      metricType: {{ .Values.keda.trigger.metricType }}
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
        metricName: {{ .Values.keda.trigger.metricName }}
        query: {{ .Values.keda.trigger.metricQuery }}
        threshold: '{{ .Values.keda.trigger.metricThreshold }}'
  {{- end }}
  {{- if .Values.keda.triggers }}
  triggers:
  {{- toYaml .Values.keda.triggers | nindent 4 }}
  {{- end }}
{{- end }}