apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-template.fullname" . }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  {{- if gt (len .Values.service.annotations) 0}}
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- range .Values.service.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "docker-template.selectorLabels" . | nindent 4 }}
