apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: {{ include "docker-template.fullname" . }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "docker-template.selectorLabels" . | nindent 6 }}
  accessLogging:
    - disabled: false
      providers:
        - name: {{ .Values.istio.telemetry.accessLogging.provider }}
