{{- if eq .Values.deploymentStrategy.kind "blueGreen" }}
{{- if .Values.deploymentStrategy.blueGreen  }}
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ include "docker-template.fullname" . }}-bluegreen
spec:
  metrics:
  - name: {{ include "docker-template.fullname" . }}-bluegreen
    count: 1
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: rollout-sync
                image: ghcr.io/porter-dev/rollout-sync:latest
                command: [sh, -c]
                args:
                {{- if .Values.deploymentStrategy.blueGreen.partnerApps }}
                - rollout sync --strategy blue-green --blue-green-apps {{ range $index, $app := .Values.deploymentStrategy.blueGreen.partnerApps }}{{ if $index }},{{ end }}{{ $app }}{{ end }}
                {{- else }}
                - rollout sync --strategy blue-green --blue-green-apps {{ include "docker-template.fullname" . }}
                {{- end }}
              restartPolicy: Never
          backoffLimit: 0
{{- end }}
{{- end }}