{{- if and (.Values.deploymentStrategy) (eq .Values.deploymentStrategy.kind "blueGreen") }}
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ include "docker-template.fullname" . }}-bluegreen
spec:
  metrics:
  - name: {{ include "docker-template.fullname" . }}-bluegreen
    count: 1
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              serviceAccountName: {{ include "docker-template.fullname" . }}-aj
              containers:
              - name: rollout-sync
                image: ghcr.io/porter-dev/rollout-sync:latest
                command: [sh, -c]
                args:
                {{- if and (.Values.deploymentStrategy.blueGreen)  (.Values.deploymentStrategy.blueGreen.partnerApps) }}
                - rollout sync --strategy blue-green --blue-green-apps {{ range $index, $app := .Values.deploymentStrategy.blueGreen.partnerApps }}{{ if $index }},{{ end }}{{ $app }}{{ end }}
                {{- else }}
                - rollout sync --strategy blue-green --blue-green-apps {{ include "docker-template.fullname" . }}
                {{- end }}
              restartPolicy: Never
          backoffLimit: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "docker-template.fullname" . }}-aj
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "docker-template.fullname" . }}-aj
subjects:
- kind: ServiceAccount
  name: {{ include "docker-template.fullname" . }}-aj
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "docker-template.fullname" . }}-aj
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docker-template.fullname" . }}-aj
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}