apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deepgram-api-config
data: 
  api.toml: |
  {{ .Values.api.config | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deepgram-engine-config
data: 
  engine.toml: |
  {{ .Values.engine.config | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deepgram-management-config
data:
  modelURLs.txt: |-
  {{ .Values.modelURLs | nindent 4 }}