apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-deepgram-disk-buffer-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-{{ .Release.Name }}-deepgram
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-deepgram-model-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-{{ .Release.Name }}-deepgram
  resources:
    requests:
      storage: 50Gi
