apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-deepgram-env-config
data:
  DEEPGRAM_API_KEY: {{ .Values.deepgramAPIKey | b64enc }}
---
apiVersion: v1
kind: Secret 
metadata:
  name: {{ .Release.Name }}-deepgram-quay-credentials 
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}