apiVersion: v1
kind: Service
metadata:
  labels:
    deepgram: api
  name: {{ .Release.Name }}-deepgram-api
spec:
  ports:
    - name: https
      port: 8080
      targetPort: https
  selector:
    deepgram: {{ .Release.Name }}-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    deepgram: engine
  name: {{ .Release.Name }}-deepgram-engine
spec:
  ports:
    - name: https
      port: 8080
      targetPort: https
  selector:
    deepgram: {{ .Release.Name }}-engine
